import {describe,expect,it} from "vitest";
import {getRegisteredTrophyAsset,hasRegisteredTrophyAsset} from "./assets";
import {buildTrophyDetails,deriveTrophyAwards,deriveTrophyEngravings,deriveTrophyRun,eventMonthYear,eventYear,resolveOwnedTrophyViewer,resolveTrophyDeepLink,shouldAnimateTrophy,shouldCloseTrophySheet,toRoman} from "./model";

describe("trophy projection",()=>{
  it("derives named and generic ranked wins in shelf order",()=>{const awards=deriveTrophyAwards("p1",[
    {player_id:"p1",tournament_id:"generic-new",placement:1},{player_id:"p1",tournament_id:"named-old",placement:1},{player_id:"p1",tournament_id:"named-new",placement:1},{player_id:"p1",tournament_id:"friendly",placement:1},{player_id:"p1",tournament_id:"second",placement:2},{player_id:"p2",tournament_id:"generic-new",placement:1},
  ],[
    {id:"generic-new",counts_as:"ranked",starts_at:"2026-09-01T00:00:00Z",timezone:"Australia/Melbourne"},{id:"named-old",counts_as:"ranked",starts_at:"2025-07-01T00:00:00Z",timezone:"Australia/Melbourne",trophy_key:"claymore",trophy_name:"The Claymore"},{id:"named-new",counts_as:"ranked",starts_at:"2026-07-01T00:00:00Z",timezone:"Australia/Melbourne",trophy_key:"claymore",trophy_name:"The Claymore"},{id:"friendly",counts_as:"exhibition"},{id:"second",counts_as:"ranked"},
  ]);expect(awards.map((award)=>award.tournamentId)).toEqual(["named-new","named-old","generic-new"]);expect(awards[2]).toMatchObject({key:"ranked_cup",name:"Ranked Cup",named:false});});
  it("formats the event year in its timezone",()=>{const award={startsAt:"2026-12-31T13:30:00Z",timezone:"Pacific/Auckland"};expect(eventYear(award)).toBe(2027);expect(eventMonthYear(award)).toBe("JAN 2027");expect(toRoman(2027)).toBe("MMXXVII");});
  it("builds a full campaign in stage order with player-oriented scores",()=>{const fixtures=[{id:"final",tournament_id:"cup",stage:"final",round_number:5,slot_number:1,player1_id:"p2",player2_id:"p1",skipped_at:null},{id:"group",tournament_id:"cup",stage:"group",round_number:1,slot_number:1,player1_id:"p1",player2_id:"p3",skipped_at:null},{id:"skipped",tournament_id:"cup",stage:"playoff",round_number:4,slot_number:1,player1_id:"p1",player2_id:"p4",skipped_at:"2026-07-01"}];const matches=[{id:"m-final",tournament_id:"cup",fixture_id:"final",player1_id:"p2",player2_id:"p1",winner_id:"p1",status:"approved",played_at:"2026-07-01",match_sets:[{set_number:1,p1_games:4,p2_games:6,tiebreak_p1:null,tiebreak_p2:null},{set_number:2,p1_games:6,p2_games:7,tiebreak_p1:5,tiebreak_p2:7}]},{id:"m-group",tournament_id:"cup",fixture_id:"group",player1_id:"p1",player2_id:"p3",winner_id:"p3",status:"approved",played_at:"2026-07-01",match_sets:[{set_number:1,p1_games:2,p2_games:3,tiebreak_p1:null,tiebreak_p2:null}]}];const run=deriveTrophyRun("p1","cup",fixtures,matches,[{id:"p2",name:"Ben",avatarUrl:"ben.png"},{id:"p3",name:"String",avatarUrl:null}]);expect(run.map((row)=>[row.stageLabel,row.won,row.opponentName])).toEqual([["R1",false,"String"],["F",true,"Ben"]]);expect(run[1]).toMatchObject({score:"6–4, 7–6 (7–5)",opponentAvatarUrl:"ben.png",isFinal:true});});
  it("maps exact cover crop and field facts without inventing a photo",()=>{const awards=deriveTrophyAwards("p1",[{player_id:"p1",tournament_id:"cup",placement:1}],[{id:"cup",counts_as:"ranked",starts_at:"2026-07-01",timezone:"Australia/Melbourne"}]);const event={id:"cup",name:"Winter Cup",counts_as:"ranked",starts_at:"2026-07-01",timezone:"Australia/Melbourne",location_name:"Northcote",structure:"round_robin",default_surface:"clay",championship_path:"top_two_final",cover_image_url:null,cover_frame_shape:"three_two",cover_zoom:"1.75",cover_offset_x:"24",cover_offset_y:"-12"};const [detail]=buildTrophyDetails("p1",awards,[event],[{tournament_id:"cup"},{tournament_id:"cup"},{tournament_id:"cup"},{tournament_id:"cup"}],[],[],[]);expect(detail).toMatchObject({coverImageUrl:null,coverFrameShape:"three_two",coverZoom:1.75,coverOffsetX:24,coverOffsetY:-12,fieldLabel:"4 players · round robin + final",surface:"clay"});});
  it("accepts only owned links, closes after 64px, and honors reduced motion",()=>{const awards=deriveTrophyAwards("p1",[{player_id:"p1",tournament_id:"mine",placement:1}],[{id:"mine",counts_as:"ranked"}]);expect(resolveTrophyDeepLink("mine",awards)).toBe("mine");expect(resolveTrophyDeepLink("theirs",awards)).toBeNull();expect(resolveTrophyDeepLink(null,awards)).toBeNull();expect(shouldCloseTrophySheet(100,163)).toBe(false);expect(shouldCloseTrophySheet(100,164)).toBe(true);expect(shouldCloseTrophySheet(164,100)).toBe(false);expect(shouldAnimateTrophy(false)).toBe(true);expect(shouldAnimateTrophy(true)).toBe(false);});
  it("registers only the physical Claymore asset and rejects generic or non-owned viewers",()=>{const claymore=getRegisteredTrophyAsset("claymore");expect(claymore).toMatchObject({modelSrc:"/trophies/claymore-v1.glb",androidAr:true,iosAr:false});expect(hasRegisteredTrophyAsset("ranked_cup")).toBe(false);const awards=deriveTrophyAwards("p1",[{player_id:"p1",tournament_id:"mine",placement:1},{player_id:"p1",tournament_id:"generic",placement:1}],[{id:"mine",counts_as:"ranked",trophy_key:"claymore",trophy_name:"The Claymore"},{id:"generic",counts_as:"ranked"}]);expect(resolveOwnedTrophyViewer("mine",awards,new Set(["claymore"]))?.key).toBe("claymore");expect(resolveOwnedTrophyViewer("generic",awards,new Set(["claymore"]))).toBeNull();expect(resolveOwnedTrophyViewer("theirs",awards,new Set(["claymore"]))).toBeNull();});
  it("derives every completed engraving oldest-first with event-local years and repeat winners",()=>{const engravings=deriveTrophyEngravings("claymore","second",[
    {id:"second",name:"Summer Claymore",status:"completed",counts_as:"ranked",trophy_key:"claymore",starts_at:"2026-12-31T13:30:00Z",timezone:"Pacific/Auckland",location_name:"Northcote"},
    {id:"first",name:"Winter Claymore",status:"completed",counts_as:"ranked",trophy_key:"claymore",starts_at:"2025-07-01T00:00:00Z",timezone:"Australia/Melbourne",location_name:"Northcote"},
    {id:"draft",name:"Future",status:"scheduled",counts_as:"ranked",trophy_key:"claymore",starts_at:"2028-01-01",timezone:"Australia/Melbourne",location_name:"Northcote"},
    {id:"other",name:"Other",status:"completed",counts_as:"ranked",trophy_key:"other",starts_at:"2024-01-01",timezone:"Australia/Melbourne",location_name:"Elsewhere"},
  ],[{player_id:"p1",tournament_id:"first",placement:1},{player_id:"p1",tournament_id:"second",placement:1},{player_id:"p2",tournament_id:"draft",placement:1},{player_id:"p2",tournament_id:"other",placement:1}],[{id:"p1",name:"Ringo",avatarUrl:null},{id:"p2",name:"Ben",avatarUrl:null}]);expect(engravings.map((engraving)=>[engraving.tournamentId,engraving.winnerName,engraving.year,engraving.selected])).toEqual([["first","Ringo",2025,false],["second","Ringo",2027,true]]);});
});
