import {describe,expect,it} from "vitest";
import {androidSceneViewerIntent,arFailureHint,isAndroidArCandidate,shouldAutoRotateTrophy,trophyViewerControls} from "./viewer";

describe("trophy viewer controls",()=>{
  it("shows Android AR only after a supported model has loaded",()=>{expect(trophyViewerControls({loaded:false,failed:false,canActivateAr:true,androidAr:true}).showArButton).toBe(false);expect(trophyViewerControls({loaded:true,failed:false,canActivateAr:true,androidAr:true})).toEqual({showArButton:true,showArUnavailable:false});expect(trophyViewerControls({loaded:true,failed:false,canActivateAr:false,androidAr:true})).toEqual({showArButton:false,showArUnavailable:true});});
  it("keeps placement available for Android Scene Viewer while capability detection settles",()=>{expect(trophyViewerControls({loaded:true,failed:false,canActivateAr:false,androidAr:true,androidCandidate:true})).toEqual({showArButton:true,showArUnavailable:false});expect(isAndroidArCandidate("Mozilla/5.0 (Linux; Android 16; Pixel 10 Pro) Chrome/140 Mobile")).toBe(true);expect(isAndroidArCandidate("Mozilla/5.0 (iPhone)")).toBe(false);const intent=androidSceneViewerIntent("/trophies/ranked-cup-v1.glb","https://ciabatta-cup.app/tournaments/cup/trophy");expect(intent).toContain("mode=ar_preferred");expect(intent).toContain(encodeURIComponent("https://ciabatta-cup.app/trophies/ranked-cup-v1.glb"));expect(intent).toContain("com.google.android.googlequicksearchbox");});
  it("keeps iOS and failed models out of the Android AR launch",()=>{expect(trophyViewerControls({loaded:true,failed:false,canActivateAr:true,androidAr:false}).showArButton).toBe(false);expect(trophyViewerControls({loaded:true,failed:true,canActivateAr:true,androidAr:true})).toEqual({showArButton:false,showArUnavailable:false});});
  it("reports failed AR without changing the viewer and honors reduced motion",()=>{expect(arFailureHint("failed")).toContain("AR could not start");expect(arFailureHint("object-placed")).toBeNull();expect(shouldAutoRotateTrophy(false)).toBe(true);expect(shouldAutoRotateTrophy(true)).toBe(false);});
});
