import Link from "next/link";
import { redirect } from "next/navigation";
import { MatchMetadataEditor } from "@/components/courts/MatchMetadataEditor";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { getSessionPlayer } from "@/lib/auth/session";
import { loadCourtOptions } from "@/lib/courts/read";
import type { Surface } from "@/lib/courts/types";
import { createClient } from "@/lib/supabase/server";

export default async function UntaggedMatchesPage(){const player=await getSessionPlayer();if(!player)redirect("/sign-in");const db=await createClient();const [{data:matches},courts]=await Promise.all([db.from("matches").select("id, played_at, location, court_id, surface, player1_id, player2_id, winner_id, status, player1:player1_id(first_name,last_name), player2:player2_id(first_name,last_name), match_sets(set_number,p1_games,p2_games)").or(`player1_id.eq.${player.id},player2_id.eq.${player.id}`).neq("status","rejected").or("court_id.is.null,surface.is.null").order("played_at",{ascending:false}),loadCourtOptions()]);return <main className="mx-auto w-full max-w-3xl flex-1 p-6"><SiteHeader role={player.role}/><Link href="/matches" className="font-mono text-[10px] uppercase text-muted underline">← Matches</Link><section className="mt-5 border-2 border-rust bg-surface p-5 shadow-[4px_4px_0_var(--color-rust)]"><p className="font-mono text-[10px] uppercase tracking-[2px] text-rust">Zeus requires better records</p><h1 className="mt-2 font-heading text-3xl font-bold">Tag courts and surfaces</h1><p className="mt-2 font-body text-sm text-muted">These edits are metadata only. Scores, points, rank, and approvals do not move.</p></section>{!matches?.length?<p className="mt-6 border-2 border-dashed border-hairline bg-surface p-8 text-center font-body text-muted">Every match is tagged. Zeus is satisfied.</p>:<ul className="mt-6 grid gap-4">{matches.map((match,index)=>{const opponent=match.player1_id===player.id?match.player2:match.player1;const row=(Array.isArray(opponent)?opponent[0]:opponent) as {first_name?:string;last_name?:string}|null;const score=(match.match_sets??[]).sort((a,b)=>a.set_number-b.set_number).map(set=>`${set.p1_games}-${set.p2_games}`).join(", ");return <li id={index?"next-match":undefined} key={match.id} className="border-2 border-ink bg-surface p-5 shadow-[3px_3px_0_var(--color-crust)]"><div className="flex items-start justify-between gap-3"><div><p className="font-heading text-lg font-bold">{match.winner_id===player.id?"W":"L"} vs {[row?.first_name,row?.last_name].filter(Boolean).join(" ")||"Non-Ciabatta opponent"}</p><p className="mt-1 font-mono text-[10px] uppercase text-muted">{new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeZone:"Australia/Melbourne"}).format(new Date(match.played_at))} · {score}</p></div><span className="border-2 border-dashed border-crust px-2 py-1 font-mono text-[9px] uppercase text-crust">{!match.court_id&&!match.surface?"No court · no surface":!match.court_id?"No court":"No surface"}</span></div><MatchMetadataEditor matchId={match.id} courts={courts} initialCourtId={match.court_id??""} initialLocation={match.location??""} initialSurface={(match.surface as Surface|null)??""}/></li>})}</ul>}</main>}

