"use client";

import Image from "next/image";
import {useCallback,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ClaymoreCupIcon} from "@/components/brand/ClaymoreCupIcon";
import {RankedCupIcon} from "@/components/brand/RankedCupIcon";
import {PlayerAvatar} from "@/components/players/PlayerAvatar";
import {eventMonthYear,eventYear,shouldAnimateTrophy,shouldCloseTrophySheet,toRoman,type TrophyAward,type TrophyDetail} from "@/lib/trophies/model";
import styles from "./TrophyCase.module.css";

const surfaceTone:Record<string,string>={clay:"bg-rust",hard:"bg-green",grass:"bg-chartreuse",synthetic:"bg-crust"};
const frameClass:Record<string,string>={wide:"aspect-[16/7]",square:"aspect-square",three_two:"aspect-[3/2]"};

function TrophyArt({award,size=72,muted=false}:{award:TrophyAward;size?:number;muted?:boolean}){const className=muted?styles.silhouette:"";return award.key==="claymore"?<ClaymoreCupIcon size={size} className={className}/>:<RankedCupIcon size={size} className={className}/>}

export function TrophyCase({awards,details,playerName,initialTrophyId}:{awards:TrophyAward[];details:TrophyDetail[];playerName:string;initialTrophyId:string|null}){
  const router=useRouter();const [selectedId,setSelectedId]=useState(initialTrophyId);const sheetRef=useRef<HTMLDivElement>(null);const triggerRef=useRef<HTMLButtonElement|null>(null);const dragStart=useRef<number|null>(null);
  const selected=details.find((detail)=>detail.award.tournamentId===selectedId)??null;
  const close=useCallback(()=>{setSelectedId(null);router.replace("/tournaments",{scroll:false});requestAnimationFrame(()=>triggerRef.current?.focus())},[router]);
  useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const sheet=sheetRef.current;const focusable=()=>Array.from(sheet?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')??[]);focusable()[0]?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();close();return}if(event.key!=="Tab")return;const items=focusable();if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",onKey)}},[close,selected]);
  const open=(award:TrophyAward,event:React.MouseEvent<HTMLButtonElement>)=>{triggerRef.current=event.currentTarget;if(shouldAnimateTrophy(window.matchMedia("(prefers-reduced-motion: reduce)").matches)){event.currentTarget.style.transformOrigin="50% 100%";event.currentTarget.animate([{transform:"rotate(0deg)"},{transform:"rotate(-5deg)"},{transform:"rotate(5deg)"},{transform:"rotate(-3deg)"},{transform:"rotate(0deg)"}],{duration:420,easing:"ease-out"})}setSelectedId(award.tournamentId);router.push(`/tournaments?trophy=${award.tournamentId}`,{scroll:false})};
  const slots=awards.length?[...awards,{tournamentId:"next",key:"ranked_cup",name:"Next cup",startsAt:"1970-01-01",timezone:"Australia/Melbourne",named:false} satisfies TrophyAward]:[];
  const shelves:TrophyAward[][]=awards.length?Array.from({length:Math.ceil(slots.length/3)},(_,index)=>slots.slice(index*3,index*3+3)):[[{tournamentId:"empty-1",key:"claymore",name:"Empty",startsAt:"1970-01-01",timezone:"Australia/Melbourne",named:false},{tournamentId:"empty-2",key:"ranked_cup",name:"Empty",startsAt:"1970-01-01",timezone:"Australia/Melbourne",named:false}]];
  return <section className="my-10" aria-labelledby="my-trophies-title"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[2px] text-muted">Your cabinet</p><h2 id="my-trophies-title" className="font-heading text-3xl font-bold">My trophies</h2></div><span className="font-mono text-[9px] uppercase tracking-[1.5px] text-muted">{awards.length?`${awards.length} on the shelf`:"Nothing yet"}</span></div><div className={styles.cabinet}><div className={styles.plaque}>My trophies</div><div className={styles.interior}>{shelves.map((shelf,index)=><div className={styles.shelf} key={index}>{shelf.map((award)=>{const placeholder=award.tournamentId.startsWith("empty")||award.tournamentId==="next";return placeholder?<div key={award.tournamentId} className="relative z-10 flex min-h-36 flex-col items-center justify-end"><TrophyArt award={award} size={award.key==="claymore"?60:66} muted/><span className={styles.nextPlate}>{award.tournamentId==="next"?"Next cup":"Empty shelf"}</span></div>:<button key={award.tournamentId} type="button" className={`${styles.trophy} relative z-10 flex flex-col items-center justify-end`} onClick={(event)=>open(award,event)} aria-label={`Open ${award.name}, ${eventYear(award)} trophy details`}><TrophyArt award={award}/><span className={styles.plate}>{award.name} · {award.named?eventYear(award):eventMonthYear(award)}</span></button>})}</div>)}{!awards.length&&<div className={`${styles.plaque} mt-5`}>Win a cup to fill this shelf</div>}</div></div>
  {selected&&<div className="fixed inset-0 z-50 flex items-end bg-ink/70" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)close()}}><div ref={sheetRef} role="dialog" aria-modal="true" aria-labelledby="trophy-sheet-title" className="max-h-[92dvh] w-full overflow-y-auto rounded-t-[18px] border-2 border-b-0 border-ink bg-cream shadow-[0_-5px_0_var(--color-ink)] sm:mx-auto sm:max-w-2xl" onPointerDown={(event)=>{dragStart.current=event.clientY}} onPointerUp={(event)=>{if(dragStart.current!==null&&shouldCloseTrophySheet(dragStart.current,event.clientY))close();dragStart.current=null}}><div className="mx-auto mt-3 h-1.5 w-12 rounded-full bg-muted"/><div className="p-5 pb-8 sm:p-7"><div className="flex items-start gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-full border-2 border-ink bg-chartreuse"><TrophyArt award={selected.award} size={38}/></div><div className="min-w-0 flex-1"><p className="font-mono text-[9px] uppercase tracking-[1.5px] text-crust">{selected.tournamentName} · Champion</p><h2 id="trophy-sheet-title" className="font-heading text-3xl font-bold">{selected.award.name}</h2></div><button type="button" onClick={close} className="grid h-11 w-11 shrink-0 place-items-center border-2 border-ink bg-surface font-mono text-lg" aria-label="Close trophy details">×</button></div><div className="mt-5 border-2 border-ink bg-[linear-gradient(#d9a05b,#9c6230)] px-3 py-2 text-center font-mono text-[10px] font-bold uppercase tracking-[1.5px] text-[#3b2008] shadow-[2px_2px_0_var(--color-ink)]">{playerName} · Champion · {toRoman(eventYear(selected.award))}</div>
  {selected.coverImageUrl&&<div className={`relative mt-5 overflow-hidden border-2 border-ink bg-row ${frameClass[selected.coverFrameShape]??frameClass.wide}`}><Image src={selected.coverImageUrl} alt={`${selected.tournamentName} tournament day`} fill sizes="(max-width: 640px) 100vw, 672px" className="object-cover" style={{transform:`translate(${selected.coverOffsetX/2}%,${selected.coverOffsetY/2}%) scale(${selected.coverZoom})`}}/></div>}
  <dl className="mt-5 grid grid-cols-2 overflow-hidden rounded-[7px] border-2 border-ink bg-surface"><Meta label="Date" value={new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeZone:selected.award.timezone}).format(new Date(selected.award.startsAt))}/><Meta label="Location" value={selected.locationName}/><Meta label="Surface" value={selected.surface?selected.surface:"Not recorded"} dot={selected.surface?surfaceTone[selected.surface]:undefined}/><Meta label="Field" value={selected.fieldLabel}/></dl><div className="mt-6"><p className="font-mono text-[9px] uppercase tracking-[2px] text-muted">The run · {selected.run.length} matches</p><ul className="mt-2">{selected.run.map((row)=><li key={row.matchId} className={`grid grid-cols-[32px_36px_minmax(0,1fr)_auto] items-center gap-2 border-b border-dashed border-hairline px-2 py-3 ${row.isFinal?"rounded-[6px] border-2 border-solid border-ink bg-chartreuse":""}`}><span className="font-mono text-[9px] font-bold uppercase">{row.stageLabel}</span><PlayerAvatar name={row.opponentName} avatarUrl={row.opponentAvatarUrl} size={32}/><span className="truncate font-heading text-sm font-bold"><i className={`mr-2 not-italic ${row.won?"text-green":"text-rust"}`}>{row.won?"W":"L"}</i>vs {row.opponentName}</span><span className="text-right font-mono text-[10px]">{row.score||"Score unavailable"}</span></li>)}</ul></div><button type="button" disabled aria-disabled="true" className="mt-6 flex min-h-16 w-full items-center gap-4 border-2 border-ink bg-chartreuse px-5 text-left opacity-70 shadow-[4px_4px_0_var(--color-ink)]"><span aria-hidden="true" className="font-mono text-2xl">◇</span><span><b className="block font-heading text-lg">See my trophy · Coming soon</b><small className="font-mono text-[8px] uppercase tracking-[1.4px]">3D and camera experience in development</small></span></button><p className="mt-5 text-center font-mono text-[8px] uppercase tracking-[1.5px] text-muted">Swipe down or press Escape to close</p></div></div></div>}</section>;
}

function Meta({label,value,dot}:{label:string;value:string;dot?:string}){return <div className="border-b border-r border-hairline p-3"><dt className="font-mono text-[8px] uppercase tracking-[1.2px] text-muted">{label}</dt><dd className="mt-1 flex items-center gap-2 font-heading text-sm font-bold capitalize">{dot&&<i className={`h-2.5 w-2.5 rounded-full border border-ink ${dot}`}/>} {value}</dd></div>}
