"use client";

import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { CourtPicker } from "@/components/courts/CourtPicker";
import { SurfaceChips } from "@/components/courts/SurfaceChips";
import { Button } from "@/components/ui/Button";
import type { CourtOption, Surface } from "@/lib/courts/types";
import { submitPlannedResult } from "@/lib/planned/actions";

export function PlannedResultForm({ id, opponentId, opponentName, external, scheduledDate, location: initialLocation, initialCourtId = "", courts }: { id:string; opponentId?:string; opponentName:string; external:boolean; scheduledDate:string; location:string; initialCourtId?:string; courts:CourtOption[] }) {
  const [type,setType]=useState<"ranked"|"exhibition">("ranked");const [format,setFormat]=useState<"one_set"|"best_of_3"|"pro_set_8"|"custom">("one_set");const [date,setDate]=useState(scheduledDate);const [location,setLocation]=useState(initialLocation);const[courtId,setCourtId]=useState(initialCourtId);const[surface,setSurface]=useState<Surface|"">("");const [selfGames,setSelfGames]=useState("");const [otherGames,setOtherGames]=useState("");const [winner,setWinner]=useState<"self"|"other">("self");const [error,setError]=useState("");const[pending,start]=useTransition();const router=useRouter();
  const submit=()=>start(async()=>{const n1=Number(selfGames),n2=Number(otherGames);const sets=[{selfGames:n1,opponentGames:n2,selfTiebreak:null,opponentTiebreak:null}];const input=external?{opponentName,saveOpponent:true,format,formatNote:"",playedDate:date,location,courtId,surface,sets}:{opponentId:opponentId!,type,format,formatNote:"",playedDate:date,location,courtId,surface,sets};if(winner==="self"&&n1<=n2||winner==="other"&&n2<=n1){setError("Make the selected winner win the set.");return;}const result=await submitPlannedResult(id,input,external);if(result.ok){setError(result.deliveryWarning?.message??"");router.refresh();}else setError("error" in result?result.error:"Couldn't submit result.");});
  return <section className="mt-6 border-2 border-ink bg-surface p-5 shadow-[3px_3px_0_var(--color-crust)]"><p className="font-mono text-[10px] uppercase tracking-[2px] text-crust">Define the result</p><div className="mt-4 grid gap-4">{!external&&<div><p className="font-mono text-[10px] uppercase text-muted">Type</p><div className="mt-2 grid grid-cols-2 gap-2">{(["ranked","exhibition"] as const).map(value=><button type="button" key={value} onClick={()=>setType(value)} className={`border-2 border-ink p-2 font-mono text-xs uppercase ${type===value?"bg-green text-cream":"bg-cream"}`}>{value === "ranked" ? "Ranked +15/+30":"Non-ranked +10"}</button>)}</div></div>}<label className="font-mono text-[10px] uppercase text-muted">Format<select value={format} onChange={e=>setFormat(e.target.value as typeof format)} className="mt-2 w-full border-2 border-ink bg-cream p-3 font-body"><option value="one_set">Single set</option><option value="best_of_3">Best of 3</option><option value="pro_set_8">Pro set</option><option value="custom">Whatever it was</option></select></label><div className="grid grid-cols-2 gap-3"><label className="font-mono text-[10px] uppercase text-muted">You<input inputMode="numeric" value={selfGames} onChange={e=>setSelfGames(e.target.value)} className="mt-2 w-full border-2 border-ink bg-cream p-3"/></label><label className="font-mono text-[10px] uppercase text-muted">{opponentName}<input inputMode="numeric" value={otherGames} onChange={e=>setOtherGames(e.target.value)} className="mt-2 w-full border-2 border-ink bg-cream p-3"/></label></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setWinner("self")} className={`border-2 border-ink p-2 font-mono text-xs ${winner==="self"?"bg-chartreuse":"bg-cream"}`}>I won</button><button type="button" onClick={()=>setWinner("other")} className={`border-2 border-ink p-2 font-mono text-xs ${winner==="other"?"bg-chartreuse":"bg-cream"}`}>{opponentName} won</button></div><label className="font-mono text-[10px] uppercase text-muted">Played<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 w-full border-2 border-ink bg-cream p-3"/></label><CourtPicker courts={courts} value={location} courtId={courtId} onChange={(name,id)=>{setLocation(name);setCourtId(id)}} label="Location"/><SurfaceChips value={surface} onChange={setSurface} preferred={courts.find((court)=>court.id===courtId)?.surfaces??[]}/>{error&&<p className="font-mono text-xs text-rust">{error}</p>}<Button loading={pending} onClick={submit}>{external?"Confirm result":"Send for approval"}</Button></div></section>;
}
