"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CourtPicker } from "@/components/courts/CourtPicker";
import { SurfaceChips } from "@/components/courts/SurfaceChips";
import { Button } from "@/components/ui/Button";
import type { CourtOption, Surface } from "@/lib/courts/types";
import { correctPlannedResult } from "@/lib/planned/actions";

type Proposal={match_type:"ranked"|"exhibition";format:"one_set"|"best_of_3"|"pro_set_8"|"custom";format_note:string|null;played_at:string;location:string|null;court_id:string|null;surface:Surface|null;score:Array<{selfGames:number;opponentGames:number}>};

export function PlannedCorrectionForm({id,opponentId,submitterName,opponentName,proposal,courts}:{id:string;opponentId:string;submitterName:string;opponentName:string;proposal:Proposal;courts:CourtOption[]}){
  const first=proposal.score[0]??{selfGames:0,opponentGames:0};const[type,setType]=useState(proposal.match_type);const[format,setFormat]=useState(proposal.format);const[self,setSelf]=useState(String(first.selfGames));const[other,setOther]=useState(String(first.opponentGames));const[date,setDate]=useState(proposal.played_at.slice(0,10));const[location,setLocation]=useState(proposal.location??"");const[courtId,setCourtId]=useState(proposal.court_id??"");const[surface,setSurface]=useState<Surface|"">(proposal.surface??"");const[error,setError]=useState("");const[pending,start]=useTransition();const router=useRouter();
  const submit=()=>start(async()=>{setError("");const result=await correctPlannedResult(id,{opponentId,type,format,formatNote:proposal.format_note??"",playedDate:date,location,courtId,surface,sets:[{selfGames:Number(self),opponentGames:Number(other),selfTiebreak:null,opponentTiebreak:null}]});if(!result.ok)setError(result.error);else router.refresh();});
  return <div className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-2">{(["ranked","exhibition"] as const).map(value=><button type="button" key={value} onClick={()=>setType(value)} className={`min-h-11 border-2 border-ink font-mono text-[10px] uppercase ${type===value?"bg-green text-cream":"bg-cream"}`}>{value}</button>)}</div><label className="font-mono text-[10px] uppercase text-muted">Format<select value={format} onChange={e=>setFormat(e.target.value as typeof format)} className="mt-1 w-full border-2 border-ink bg-cream p-3"><option value="one_set">One set</option><option value="best_of_3">Best of 3</option><option value="pro_set_8">Pro set 8</option><option value="custom">Custom</option></select></label><div className="grid grid-cols-2 gap-3"><label className="font-mono text-[10px] uppercase text-muted">{submitterName}<input inputMode="numeric" value={self} onChange={e=>setSelf(e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label><label className="font-mono text-[10px] uppercase text-muted">{opponentName}<input inputMode="numeric" value={other} onChange={e=>setOther(e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label></div><label className="font-mono text-[10px] uppercase text-muted">Played<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label><CourtPicker courts={courts} value={location} courtId={courtId} onChange={(name,nextId)=>{setLocation(name);setCourtId(nextId)}} label="Location"/><SurfaceChips value={surface} onChange={setSurface} preferred={courts.find(c=>c.id===courtId)?.surfaces??[]}/>{error&&<p className="font-mono text-[10px] text-rust" aria-live="polite">{error}</p>}<Button loading={pending} loadingLabel="Saving correction..." onClick={submit}>Save corrected proposal</Button><p className="font-mono text-[9px] uppercase text-muted">The original stays in the audit chain. The other player must confirm this revision.</p></div>;
}
