import { notFound, redirect } from "next/navigation";
import { ApproveResultButton } from "@/components/planned/ApproveResultButton";
import { PlannedActions } from "@/components/planned/PlannedActions";
import { PlannedResultForm } from "@/components/planned/PlannedResultForm";
import { getSessionPlayer } from "@/lib/auth/session";
import { loadCourtOptions } from "@/lib/courts/read";
import { createClient } from "@/lib/supabase/server";

export default async function PlannedMatchPage({params}:{params:Promise<{plannedMatchId:string}>}) {
  const player=await getSessionPlayer(); if(!player)redirect("/sign-in"); const db=await createClient(); const id=(await params).plannedMatchId;
  const [{data:plan},{data:proposal},courts]=await Promise.all([db.from("planned_matches").select("*, opponent:opponent_player_id(first_name,last_name), external:opponent_external_id(display_name)").eq("id",id).single(),db.from("planned_match_results").select("*").eq("planned_match_id",id).eq("status","pending").maybeSingle(),loadCourtOptions()]);
  if(!plan)notFound(); const invited=plan.opponent_player_id===player.id; const external=Boolean(plan.opponent_external_id); const opponent=plan.opponent as {first_name?:string;last_name?:string}|null; const externalOpponent=plan.external as {display_name?:string}|null; const name=externalOpponent?.display_name??([opponent?.first_name,opponent?.last_name].filter(Boolean).join(" ")||"Opponent"); const canReport=plan.status==="locked_in"&&(player.id===plan.created_by||player.id===plan.opponent_player_id); const canApprove=plan.status==="awaiting_result_approval"&&proposal?.submitted_by!==player.id;
  return <main className="mx-auto w-full max-w-md flex-1 p-6"><section className="border-2 border-ink bg-surface p-6 shadow-[3px_3px_0_var(--color-ink)]"><p className="font-mono text-[10px] uppercase tracking-[2px] text-green">{plan.status.replaceAll("_"," ")}</p><h1 className="mt-2 font-heading text-3xl font-bold">vs {name}</h1><dl className="mt-6 grid gap-4 font-body"><div><dt className="font-mono text-[10px] uppercase text-muted">When</dt><dd>{new Intl.DateTimeFormat("en-AU",{dateStyle:"full",timeStyle:"short"}).format(new Date(plan.scheduled_at))}</dd></div><div><dt className="font-mono text-[10px] uppercase text-muted">Where</dt><dd>{plan.location||"To be decided"}</dd></div><div><dt className="font-mono text-[10px] uppercase text-muted">Stakes</dt><dd className="border-2 border-dashed border-ink p-2 font-mono text-xs">Undecided — settle it after you play</dd></div></dl><div className="mt-6"><PlannedActions id={plan.id} invited={invited} status={plan.status}/></div></section>{canReport&&<PlannedResultForm id={plan.id} opponentId={plan.opponent_player_id??undefined} opponentName={name} external={external} scheduledDate={String(plan.scheduled_at).slice(0,10)} location={plan.location} initialCourtId={plan.court_id??""} courts={courts}/>} {canApprove&&<section className="mt-6 border-2 border-ink bg-surface p-5"><p className="font-mono text-[10px] uppercase text-crust">Awaiting your approval</p><p className="mt-2 font-body text-sm">If this is how it went, confirm it. Ranked results still go to the organiser.</p><div className="mt-4"><ApproveResultButton id={plan.id}/></div></section>}</main>;
}
