"use client";

import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { SurfaceChips } from "@/components/courts/SurfaceChips";
import type { Surface } from "@/lib/courts/types";
import { resubmitQueriedMatch } from "@/lib/match/actions";

type SetRow={selfGames:number;opponentGames:number;selfTiebreak:number|null;opponentTiebreak:number|null};
export function QueriedMatchResubmitForm({matchId,opponentId,opponentName,type:initialType,format,formatNote,playedDate,location:initialLocation,surface:initialSurface,initialSets}:{matchId:string;opponentId:string;opponentName:string;type:"ranked"|"exhibition";format:"one_set"|"best_of_3"|"pro_set_8"|"custom";formatNote:string|null;playedDate:string;location:string;surface:Surface|null;initialSets:SetRow[]}){
  const[type,setType]=useState(initialType);const[date,setDate]=useState(playedDate);const[location,setLocation]=useState(initialLocation);const[surface,setSurface]=useState<Surface|"">(initialSurface??"");const[sets,setSets]=useState(initialSets.map(s=>({self:String(s.selfGames),other:String(s.opponentGames),selfTb:s.selfTiebreak==null?"":String(s.selfTiebreak),otherTb:s.opponentTiebreak==null?"":String(s.opponentTiebreak)})));const[error,setError]=useState("");const[pending,start]=useTransition();const router=useRouter();
  const update=(index:number,key:"self"|"other",value:string)=>setSets(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));
  const submit=()=>start(async()=>{setError("");const result=await resubmitQueriedMatch(matchId,{opponentId,type,format,formatNote:formatNote??"",playedDate:date,location,surface,sets:sets.map(row=>({selfGames:Number(row.self),opponentGames:Number(row.other),selfTiebreak:row.selfTb===""?null:Number(row.selfTb),opponentTiebreak:row.otherTb===""?null:Number(row.otherTb)}))});if(!result.ok)setError(result.error);else router.refresh();});
  return <div className="mt-4 grid gap-3 border-t-2 border-hairline pt-4"><p className="font-mono text-[10px] uppercase text-rust">Correct and resend</p><div className="grid grid-cols-2 gap-2">{(["ranked","exhibition"] as const).map(value=><button type="button" key={value} onClick={()=>setType(value)} className={`min-h-11 border-2 border-ink font-mono text-[10px] uppercase ${type===value?"bg-green text-cream":"bg-cream"}`}>{value}</button>)}</div>{sets.map((row,index)=><div key={index} className="grid grid-cols-2 gap-3"><label className="font-mono text-[9px] uppercase text-muted">You · set {index+1}<input inputMode="numeric" value={row.self} onChange={e=>update(index,"self",e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label><label className="font-mono text-[9px] uppercase text-muted">{opponentName}<input inputMode="numeric" value={row.other} onChange={e=>update(index,"other",e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label></div>)}<label className="font-mono text-[9px] uppercase text-muted">Played<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label><label className="font-mono text-[9px] uppercase text-muted">Location<input value={location} onChange={e=>setLocation(e.target.value)} className="mt-1 w-full border-2 border-ink bg-cream p-3"/></label><SurfaceChips value={surface} onChange={setSurface}/>{error&&<p className="font-mono text-[10px] text-rust" aria-live="polite">{error}</p>}<Button loading={pending} loadingLabel="Resending..." onClick={submit}>Resend for confirmation</Button></div>;
}
