"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { TrophyBadge } from "@/components/brand/TrophyBadge";
import { PlayerAvatar } from "@/components/players/PlayerAvatar";
import { CalendarEventVisual } from "./CalendarEventVisual";
import { calendarHref, clampCalendarRange, monthGrid, parseCalendarState, presetRange, transitionCalendarState } from "@/lib/calendar/range";
import { deriveCalendarScorecard, eventsInRange, groupCalendarEvents, recentHistoricEvents } from "@/lib/calendar/model";
import type { CalendarData, CalendarEvent, CalendarPreset, CalendarUrlState } from "@/lib/calendar/types";

const eyebrow = "font-mono text-[10px] uppercase tracking-[2px] text-muted";
const focus = "outline-none focus-visible:ring-2 focus-visible:ring-green focus-visible:ring-offset-2";
const kindLabel: Record<CalendarEvent["kind"], string> = { ranked: "Ranked", exhibition: "Exhibition", external: "Non-Ciabatta", cup: "Cup", practice: "Practice", planned: "Planned" };
const kindTone: Record<CalendarEvent["kind"], string> = { ranked: "bg-green text-cream", exhibition: "bg-crust text-cream", external: "border border-dashed border-green bg-surface text-green", cup: "bg-chartreuse text-ink", practice: "bg-row text-green", planned: "bg-ink text-cream" };
const outcomeTone: Record<CalendarEvent["outcome"]["tone"], string> = { win: "bg-green text-cream", loss: "bg-rust text-cream", neutral: "bg-row text-muted", future: "border border-ink bg-surface text-ink" };

export function CalendarExperience({ data, state: initialState }: { data: CalendarData; state: CalendarUrlState }) {
  const [state, setState] = useState(initialState);
  useEffect(() => {
    const restore = () => setState(parseCalendarState(Object.fromEntries(new URLSearchParams(window.location.search)), data.today));
    window.addEventListener("popstate", restore);
    return () => window.removeEventListener("popstate", restore);
  }, [data.today]);
  const go = useCallback((changes: Partial<CalendarUrlState>) => {
    const next = transitionCalendarState(state, changes);
    setState(next);
    window.history.pushState(null, "", calendarHref(next, {}));
  }, [state]);

  const visibleEvents = eventsInRange(data.events, state.from, state.to, state.showExternal);
  const score = deriveCalendarScorecard(data.events, data.ledger, data.timeline, state.from, state.to, state.showExternal);
  const selectedEvent = data.events.find((event) => event.key === state.event) ?? null;
  const selectedDayEvents = state.day ? data.events.filter((event) => event.date === state.day && (state.showExternal || event.kind !== "external")) : [];
  if (state.screen === "event" && selectedEvent) return <EventDetail event={selectedEvent} state={state} go={go}/>;
  if (state.screen === "day" && state.day) return <DayDetail day={state.day} events={selectedDayEvents} go={go}/>;

  return <>
    <header className="mb-6 sm:flex sm:items-end sm:justify-between"><div><p className={eyebrow}>Your season · one canonical ledger</p><h1 className="font-heading text-3xl font-bold sm:text-5xl">My tennis calendar</h1></div><p className="mt-2 font-mono text-[10px] uppercase text-green sm:text-right">Melbourne time · Rank #{data.rank ?? "—"} · {data.currentPoints} pts</p></header>
    <div className="grid gap-6 lg:grid-cols-[320px_minmax(0,1fr)]">
      <aside className="grid gap-4 self-start lg:sticky lg:top-4">
        <Scorecard data={data} score={score}/>
        <RecentHistory events={data.events} showExternal={state.showExternal} onOpen={(event) => go({ screen:"event", event:event.key, back:"calendar", day:event.date })}/>
        {data.nextOnCourt && (
          <NextOnCourt event={data.nextOnCourt} onOpen={() => go({ screen:"event", event:data.nextOnCourt!.key, back:"calendar", day:data.nextOnCourt!.date })}/>
        )}
        <section className="hidden border-2 border-ink bg-surface p-4 lg:block"><p className={eyebrow}>Legend & settings</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(kindLabel).map(([kind, label]) => <span key={kind} className={`px-2 py-1 font-mono text-[9px] uppercase ${kindTone[kind as CalendarEvent["kind"]]}`}>{label}</span>)}</div><button onClick={() => go({ showExternal: !state.showExternal })} className={`mt-4 font-mono text-[10px] uppercase text-green underline ${focus}`}>Non-Ciabatta: {state.showExternal ? "shown" : "hidden"}</button><button onClick={() => go({ weekStart: state.weekStart === "mon" ? "sun" : "mon" })} className={`ml-4 mt-4 font-mono text-[10px] uppercase text-green underline ${focus}`}>Week: {state.weekStart}</button></section>
      </aside>
      <section className="min-w-0">
        <Controls state={state} today={data.today} go={go}/>
        {state.view === "grid"
          ? <CalendarGrid data={data} state={state} events={visibleEvents} go={go}/>
          : <CalendarList events={visibleEvents} today={data.today} go={go}/>
        }
      </section>
    </div>
  </>;
}

function Scorecard({ data, score }: { data: CalendarData; score: ReturnType<typeof deriveCalendarScorecard> }) {
  return <section className="border-2 border-ink bg-ink p-4 text-cream shadow-[4px_4px_0_var(--color-green)] sm:p-5"><div className="flex items-center gap-3"><PlayerAvatar name={data.player.name} avatarUrl={data.player.avatarUrl} size={48}/><div><p className="font-heading text-lg font-bold">{data.player.name}</p><p className="font-mono text-[9px] uppercase text-green-muted">{score.form} form · {score.won}-{score.lost} record</p></div></div><div className="mt-4 grid grid-cols-3 border-y border-muted-dark py-3 text-center"><Metric label="Pts earned" value={`+${score.pointsEarned}`}/><Metric label="Decay" value={`−${score.decay}`}/><Metric label="Net" value={`${score.net >= 0 ? "+" : ""}${score.net}`}/></div><div className="mt-3 grid grid-cols-2 gap-3 font-mono text-[9px] uppercase text-green-muted"><span>Win streak <strong className="block text-lg text-chartreuse">{score.streak}</strong></span><span>Best surface <strong className="block truncate text-sm text-chartreuse">{score.bestSurface ?? "—"}</strong></span></div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="font-mono text-[8px] uppercase text-green-muted">{label}</p><p className="mt-1 font-mono text-xl font-bold text-chartreuse">{value}</p></div>; }

function RecentHistory({ events, showExternal, onOpen }: { events: CalendarEvent[]; showExternal: boolean; onOpen: (event: CalendarEvent) => void }) {
  const rows = recentHistoricEvents(events, showExternal);
  const content = rows.length ? <div className="grid gap-2">{rows.map((event) => <button key={event.key} onClick={() => onOpen(event)} className={`flex w-full items-center gap-3 border border-ink bg-surface p-2 text-left active:translate-x-px active:translate-y-px ${focus}`}><CalendarEventVisual event={event} size="compact"/><div className="min-w-0 flex-1"><p className="truncate font-heading text-sm font-bold">{event.title}</p><p className={`mt-1 inline-block px-1.5 py-0.5 font-mono text-[7px] uppercase ${outcomeTone[event.outcome.tone]}`}>{event.outcome.label}</p><p className="mt-1 font-mono text-[8px] uppercase text-muted">{formatDateKey(event.date, false)}</p></div></button>)}</div> : <p className="font-body text-sm text-muted">No completed events yet.</p>;
  return <><section className="hidden border-2 border-ink bg-surface p-4 lg:block"><p className={`${eyebrow} mb-3`}>Recent history</p>{content}</section><details className="border-2 border-ink bg-surface lg:hidden"><summary className="cursor-pointer p-4 font-mono text-[10px] uppercase tracking-[2px] text-green">Recent history · {rows.length}</summary><div className="border-t-2 border-ink p-3">{content}</div></details></>;
}

function NextOnCourt({ event, onOpen }: { event: CalendarEvent; onOpen: () => void }) { return <button onClick={onOpen} className={`w-full border-2 border-ink bg-surface p-4 text-left shadow-[3px_3px_0_var(--color-crust)] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none ${focus}`}><p className={eyebrow}>Next on court</p><div className="mt-3 flex items-center gap-3"><CalendarEventVisual event={event} size="compact"/><div><p className="font-heading text-lg font-bold">{event.title}</p><p className="font-mono text-[9px] uppercase text-crust">{event.outcome.label} · {formatDay(event.startsAt, true)}</p></div></div></button>; }

function Controls({ state, today, go }: { state: CalendarUrlState; today: string; go: (changes: Partial<CalendarUrlState>) => void }) {
  const applyPreset = (preset: Exclude<CalendarPreset, "custom">) => go({ preset, ...presetRange(today, preset) });
  return <div className="mb-4 border-2 border-ink bg-surface p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1">{(["7d", "14d", "30d"] as const).map((preset) => <button key={preset} onClick={() => applyPreset(preset)} className={`border px-3 py-2 font-mono text-[9px] uppercase active:translate-y-px ${focus} ${state.preset === preset ? "border-ink bg-ink text-chartreuse" : "border-hairline"}`}>{preset}</button>)}<button onClick={() => go({ preset: "custom" })} className={`border px-3 py-2 font-mono text-[9px] uppercase active:translate-y-px ${focus} ${state.preset === "custom" ? "border-ink bg-ink text-chartreuse" : "border-hairline"}`}>Custom</button></div><div className="flex border border-ink"><button onClick={() => go({ view: "grid", screen: "calendar" })} aria-pressed={state.view === "grid"} className={`px-3 py-2 font-mono text-[9px] uppercase ${focus} ${state.view === "grid" ? "bg-green text-cream" : ""}`}>Grid</button><button onClick={() => go({ view: "list", screen: "calendar" })} aria-pressed={state.view === "list"} className={`px-3 py-2 font-mono text-[9px] uppercase ${focus} ${state.view === "list" ? "bg-green text-cream" : ""}`}>List</button></div></div>{state.preset === "custom" && <div className="mt-3 flex items-center gap-2"><input aria-label="Range start" type="date" value={state.from} onChange={(event) => go({ preset:"custom", ...clampCalendarRange(event.target.value, state.to, "from") })} className="min-w-0 flex-1 border border-ink bg-cream p-2 font-mono text-[10px]"/><span>—</span><input aria-label="Range end" type="date" value={state.to} onChange={(event) => go({ preset:"custom", ...clampCalendarRange(state.from, event.target.value, "to") })} className="min-w-0 flex-1 border border-ink bg-cream p-2 font-mono text-[10px]"/></div>}</div>;
}

function CalendarGrid({ data, state, events, go }: { data: CalendarData; state: CalendarUrlState; events: CalendarEvent[]; go: (changes: Partial<CalendarUrlState>) => void }) {
  const cells = monthGrid(state.month, state.weekStart); const byDay = groupCalendarEvents(events); const monthDate = new Date(`${state.month}-01T12:00:00Z`); const labels = state.weekStart === "mon" ? ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] : ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
  const shiftMonth = (delta: number) => { const next = new Date(monthDate); next.setUTCMonth(next.getUTCMonth() + delta); return next.toISOString().slice(0, 7); };
  return <section className="border-2 border-ink bg-surface shadow-[4px_4px_0_var(--color-ink)]"><header className="flex items-center justify-between border-b-2 border-ink p-4"><button onClick={() => go({ month:shiftMonth(-1) })} aria-label="Previous month" className={`font-mono text-xl active:-translate-x-1 ${focus}`}>←</button><h2 className="font-heading text-xl font-bold">{new Intl.DateTimeFormat("en-AU", { month:"long", year:"numeric", timeZone:"UTC" }).format(monthDate)}</h2><button onClick={() => go({ month:shiftMonth(1) })} aria-label="Next month" className={`font-mono text-xl active:translate-x-1 ${focus}`}>→</button></header><div className="grid grid-cols-7 border-b border-hairline">{labels.map((label) => <span key={label} className="p-2 text-center font-mono text-[8px] uppercase text-muted">{label}</span>)}</div><div className="grid grid-cols-7">{cells.map((day) => { const rows = byDay.get(day) ?? []; const current = day.startsWith(state.month); return <button key={day} onClick={() => go({ screen:"day", day, back:"calendar" })} aria-label={`Open ${formatDateKey(day)}${rows.length ? `, ${rows.length} events` : ""}`} className={`min-h-16 border-b border-r border-hairline p-1.5 text-left transition-colors active:bg-ink active:text-cream sm:min-h-24 ${focus} ${current ? "" : "bg-row text-muted"} ${day === data.today ? "outline-2 -outline-offset-2 outline-green" : ""}`}><span className="font-mono text-[9px] font-bold">{Number(day.slice(-2))}</span><div className="mt-1 flex flex-wrap gap-1 sm:hidden">{rows.slice(0,4).map((event) => <i key={event.key} className={`h-2 w-2 rounded-full ${event.kind === "ranked" ? "bg-green" : event.kind === "cup" ? "bg-chartreuse" : event.kind === "planned" ? "bg-ink" : "bg-crust"}`}/>)}</div><div className="mt-1 hidden space-y-1 sm:block">{rows.slice(0,3).map((event) => <span key={event.key} className={`block truncate px-1 py-0.5 font-mono text-[7px] uppercase ${kindTone[event.kind]}`}>{event.kind === "cup" && <TrophyBadge size={10} className="inline"/>}{event.title}</span>)}</div></button>; })}</div></section>;
}

function CalendarList({ events, today, go }: { events: CalendarEvent[]; today: string; go: (changes: Partial<CalendarUrlState>) => void }) { const groups = groupCalendarEvents(events); return <div className="space-y-6">{[...groups.entries()].map(([day, rows]) => <section key={day}>{day === today && <div className="mb-3 flex items-center gap-3"><span className="h-px flex-1 bg-green"/><span className="font-mono text-[9px] uppercase text-green">Today</span><span className="h-px flex-1 bg-green"/></div>}<p className={`${eyebrow} mb-2`}>{formatDateKey(day)}</p><div className="grid gap-3">{rows.map((event) => <EventRow key={event.key} event={event} onOpen={() => go({ screen:"event", event:event.key, back:"list", day:event.date })}/>)}</div></section>)}</div>; }

function EventRow({ event, onOpen }: { event: CalendarEvent; onOpen: () => void }) { return <button onClick={onOpen} className={`flex w-full items-center gap-3 border-2 bg-surface p-3 text-left active:translate-x-[2px] active:translate-y-[2px] ${focus} ${event.kind === "external" ? "border-dashed border-muted" : "border-ink shadow-[3px_3px_0_var(--color-ink)] active:shadow-none"}`}><CalendarEventVisual event={event} size="compact"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`px-2 py-1 font-mono text-[8px] uppercase ${kindTone[event.kind]}`}>{kindLabel[event.kind]}</span><span className={`px-2 py-1 font-mono text-[8px] font-bold uppercase ${outcomeTone[event.outcome.tone]}`}>{event.outcome.label}</span></div><p className="mt-2 truncate font-heading font-bold">{event.title}</p><p className="mt-1 truncate font-mono text-[9px] uppercase text-muted">{event.outcome.detail} · {eventMetadata(event)}{event.metadataMissing ? " · metadata missing" : ""}</p></div><div className="shrink-0 text-right"><p className="font-mono text-sm font-bold text-green">{event.points ? `+${event.points}` : "—"}</p><p className="font-mono text-[8px] uppercase text-muted">{event.status === "past" ? "Past" : "Future"}</p></div></button>; }

function DayDetail({ day, events, go }: { day: string; events: CalendarEvent[]; go: (changes: Partial<CalendarUrlState>) => void }) { return <section className="mx-auto max-w-3xl"><CalendarBackButton onClick={() => go({ screen:"calendar" })}>Calendar</CalendarBackButton><header className="mt-7 border-2 border-ink bg-ink p-5 text-cream shadow-[4px_4px_0_var(--color-green)]"><p className="font-mono text-[10px] uppercase tracking-[2px] text-green-muted">Day detail · {events.length} {events.length === 1 ? "event" : "events"}</p><h1 className="mt-1 font-heading text-3xl font-bold sm:text-4xl">{formatDateKey(day)}</h1></header><div className="mt-6 grid gap-4">{events.length ? events.map((event) => <DayEventCard key={event.key} event={event} onOpen={() => go({ screen:"event", event:event.key, back:"day", day })}/>) : <p className="border-2 border-dashed border-hairline bg-surface p-6 text-muted">No tennis recorded on this day.</p>}</div></section>; }

function DayEventCard({ event, onOpen }: { event: CalendarEvent; onOpen: () => void }) { return <button onClick={onOpen} className={`w-full overflow-hidden border-2 bg-surface text-left active:translate-x-[2px] active:translate-y-[2px] ${focus} ${event.kind === "external" ? "border-dashed border-muted" : "border-ink shadow-[4px_4px_0_var(--color-ink)] active:shadow-none"}`}><CalendarEventVisual event={event} size="card"/><div className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className={`px-2 py-1 font-mono text-[8px] uppercase ${kindTone[event.kind]}`}>{kindLabel[event.kind]}</span><span className={`px-2 py-1 font-mono text-[8px] font-bold uppercase ${outcomeTone[event.outcome.tone]}`}>{event.outcome.label}</span></div><h2 className="mt-3 font-heading text-lg font-bold">{event.title}</h2><p className="mt-1 font-mono text-[9px] uppercase text-muted">{event.outcome.detail} · {eventMetadata(event)}</p><div className="mt-3 flex items-end justify-between"><span className="font-mono text-[9px] uppercase text-green underline">Open →</span><span className="font-mono text-lg font-bold text-green">{event.points ? `+${event.points}` : "—"}</span></div></div></button>; }

function EventDetail({ event, state, go }: { event: CalendarEvent; state: CalendarUrlState; go: (changes: Partial<CalendarUrlState>) => void }) { const backToDay = state.back === "day" && state.day; return <section className="mx-auto max-w-3xl"><CalendarBackButton onClick={() => backToDay ? go({ screen:"day", event:null }) : go({ screen:"calendar", view:state.back === "list" ? "list" : state.view })}>{backToDay ? "Day" : state.back === "list" ? "List" : "Calendar"}</CalendarBackButton><article className="mt-7 overflow-hidden border-2 border-ink bg-surface shadow-[5px_5px_0_var(--color-ink)]"><CalendarEventVisual event={event} size="hero"/><div className="p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className={`inline-block px-2 py-1 font-mono text-[9px] uppercase ${kindTone[event.kind]}`}>{kindLabel[event.kind]}</span><span className={`inline-block px-2 py-1 font-mono text-[9px] font-bold uppercase ${outcomeTone[event.outcome.tone]}`}>{event.outcome.label}</span></div><h1 className="mt-3 font-heading text-3xl font-bold">{event.title}</h1><p className="mt-1 font-mono text-[10px] uppercase text-muted">{formatDay(event.startsAt, true)} · {event.status === "past" ? "Past" : "Future"}</p></div>{event.kind === "cup" && <TrophyBadge size={42}/>}</div><div className="mt-6 grid gap-4 border-y border-hairline py-5 sm:grid-cols-3"><Detail label="Result" value={event.outcome.detail}/><Detail label="Points" value={event.points ? `+${event.points}` : "—"}/><Detail label="Surface" value={event.surface ?? "Not recorded"}/><Detail label="Court" value={event.kind === "practice" ? "Not recorded" : event.court ?? event.location ?? "Not recorded"}/>{event.record && <Detail label="Fixture record" value={`${event.record.won}-${event.record.lost}`}/>} </div>{event.metadataMissing && <Link href="/matches/untagged" className="mt-5 block border border-dashed border-crust p-3 font-mono text-[10px] uppercase text-crust">Complete missing court or surface →</Link>}<Link href={event.href} className="mt-6 inline-block font-mono text-[11px] uppercase text-green underline decoration-2 underline-offset-4">Open source record →</Link></div></article></section>; }

function CalendarBackButton({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`inline-flex min-h-8 items-center gap-1 font-mono text-[10px] uppercase tracking-[1.4px] text-muted underline decoration-green decoration-2 underline-offset-4 ${focus}`}><span aria-hidden="true">←</span><span>{children}</span></button>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className={eyebrow}>{label}</p><p className="mt-1 font-heading font-bold">{value}</p></div>; }
function eventMetadata(event: CalendarEvent) { if (event.kind === "practice") return "Court · Not recorded"; return [event.surface, event.court ?? event.location].filter(Boolean).join(" · ") || "Location not recorded"; }
function formatDateKey(day: string, includeYear = true) { return new Intl.DateTimeFormat("en-AU", { weekday:"long", day:"numeric", month:"long", ...(includeYear ? { year:"numeric" } : {}), timeZone:"UTC" }).format(new Date(`${day}T12:00:00Z`)); }
function formatDay(value: string, time = false) { return new Intl.DateTimeFormat("en-AU", { weekday:"short", day:"numeric", month:"short", ...(time ? { hour:"numeric", minute:"2-digit" } : {}), timeZone:"Australia/Melbourne" }).format(new Date(value)); }
