"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { PlayerAvatar } from "@/components/players/PlayerAvatar";
import { TrophyBadge } from "@/components/brand/TrophyBadge";
import { BackLink } from "@/components/ui/BackLink";
import { calendarHref, clampCalendarRange, monthGrid, presetRange } from "@/lib/calendar/range";
import { deriveCalendarScorecard, eventsInRange, groupCalendarEvents } from "@/lib/calendar/model";
import type { CalendarData, CalendarEvent, CalendarPreset, CalendarUrlState } from "@/lib/calendar/types";

const eyebrow = "font-mono text-[10px] uppercase tracking-[2px] text-muted";
const kindLabel: Record<CalendarEvent["kind"], string> = { ranked: "Ranked", exhibition: "Exhibition", external: "Non-Ciabatta", cup: "Cup", practice: "Practice", planned: "Planned" };
const kindTone: Record<CalendarEvent["kind"], string> = { ranked: "bg-green text-cream", exhibition: "bg-crust text-cream", external: "border border-dashed border-green bg-surface text-green", cup: "bg-chartreuse text-ink", practice: "bg-row text-green", planned: "bg-ink text-cream" };

export function CalendarExperience({ data, state }: { data: CalendarData; state: CalendarUrlState }) {
  const router = useRouter();
  const allVisible = eventsInRange(data.events, state.from, state.to, state.showExternal);
  const score = deriveCalendarScorecard(data.events, data.ledger, data.timeline, state.from, state.to, state.showExternal);
  const go = (changes: Partial<CalendarUrlState>) => router.push(calendarHref(state, changes));
  const selectedEvent = data.events.find((event) => event.key === state.event) ?? null;
  const selectedDayEvents = state.day ? data.events.filter((event) => event.date === state.day && (state.showExternal || event.kind !== "external")) : [];
  if (state.screen === "event" && selectedEvent) return <EventDetail event={selectedEvent} state={state}/>;
  if (state.screen === "day" && state.day) return <DayDetail day={state.day} events={selectedDayEvents} state={state}/>;

  return <>
    <header className="mb-6 sm:flex sm:items-end sm:justify-between"><div><p className={eyebrow}>Your season · one canonical ledger</p><h1 className="font-heading text-3xl font-bold sm:text-5xl">My tennis calendar</h1></div><p className="mt-2 font-mono text-[10px] uppercase text-green sm:text-right">Melbourne time · Rank #{data.rank ?? "—"} · {data.currentPoints} pts</p></header>
    <div className="grid gap-6 lg:grid-cols-[320px_minmax(0,1fr)]">
      <aside className="grid gap-4 self-start lg:sticky lg:top-4">
        <Scorecard data={data} score={score}/>
        {data.nextOnCourt && <NextOnCourt event={data.nextOnCourt} state={state}/>}
        <section className="hidden border-2 border-ink bg-surface p-4 lg:block"><p className={eyebrow}>Legend & settings</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(kindLabel).map(([kind, label]) => <span key={kind} className={`px-2 py-1 font-mono text-[9px] uppercase ${kindTone[kind as CalendarEvent["kind"]]}`}>{label}</span>)}</div><button onClick={() => go({ showExternal: !state.showExternal })} className="mt-4 font-mono text-[10px] uppercase text-green underline">Non-Ciabatta: {state.showExternal ? "shown" : "hidden"}</button><button onClick={() => go({ weekStart: state.weekStart === "mon" ? "sun" : "mon" })} className="ml-4 mt-4 font-mono text-[10px] uppercase text-green underline">Week: {state.weekStart}</button></section>
      </aside>
      <section className="min-w-0">
        <Controls state={state} today={data.today} go={go}/>
        {state.view === "grid" ? <CalendarGrid data={data} state={state} events={allVisible}/> : <CalendarList events={allVisible} today={data.today} state={state}/>}
      </section>
    </div>
  </>;
}

function Scorecard({ data, score }: { data: CalendarData; score: ReturnType<typeof deriveCalendarScorecard> }) {
  return <section className="border-2 border-ink bg-ink p-4 text-cream shadow-[4px_4px_0_var(--color-green)] sm:p-5"><div className="flex items-center gap-3"><PlayerAvatar name={data.player.name} avatarUrl={data.player.avatarUrl} size={48}/><div><p className="font-heading text-lg font-bold">{data.player.name}</p><p className="font-mono text-[9px] uppercase text-green-muted">{score.form} form · {score.won}-{score.lost} record</p></div></div><div className="mt-4 grid grid-cols-3 border-y border-muted-dark py-3 text-center"><Metric label="Pts earned" value={`+${score.pointsEarned}`}/><Metric label="Decay" value={`−${score.decay}`}/><Metric label="Net" value={`${score.net >= 0 ? "+" : ""}${score.net}`}/></div><div className="mt-3 grid grid-cols-2 gap-3 font-mono text-[9px] uppercase text-green-muted"><span>Win streak <strong className="block text-lg text-chartreuse">{score.streak}</strong></span><span>Best surface <strong className="block truncate text-sm text-chartreuse">{score.bestSurface ?? "—"}</strong></span></div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="font-mono text-[8px] uppercase text-green-muted">{label}</p><p className="mt-1 font-mono text-xl font-bold text-chartreuse">{value}</p></div>; }
function NextOnCourt({ event, state }: { event: CalendarEvent; state: CalendarUrlState }) { return <Link href={calendarHref(state, { screen: "event", event: event.key, back: "calendar" })} className="block border-2 border-ink bg-surface p-4 shadow-[3px_3px_0_var(--color-crust)]"><p className={eyebrow}>Next on court</p><p className="mt-2 font-heading text-lg font-bold">{event.title}</p><p className="font-mono text-[9px] uppercase text-crust">{event.subtitle} · {formatDay(event.startsAt, true)}</p></Link>; }

function Controls({ state, today, go }: { state: CalendarUrlState; today: string; go: (changes: Partial<CalendarUrlState>) => void }) {
  const applyPreset = (preset: Exclude<CalendarPreset, "custom">) => go({ preset, ...presetRange(today, preset) });
  return <div className="mb-4 border-2 border-ink bg-surface p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1">{(["7d", "14d", "30d"] as const).map((preset) => <button key={preset} onClick={() => applyPreset(preset)} className={`border px-3 py-2 font-mono text-[9px] uppercase ${state.preset === preset ? "border-ink bg-ink text-chartreuse" : "border-hairline"}`}>{preset}</button>)}<button onClick={() => go({ preset: "custom" })} className={`border px-3 py-2 font-mono text-[9px] uppercase ${state.preset === "custom" ? "border-ink bg-ink text-chartreuse" : "border-hairline"}`}>Custom</button></div><div className="flex border border-ink"><button onClick={() => go({ view: "grid", screen: "calendar" })} className={`px-3 py-2 font-mono text-[9px] uppercase ${state.view === "grid" ? "bg-green text-cream" : ""}`}>Grid</button><button onClick={() => go({ view: "list", screen: "calendar" })} className={`px-3 py-2 font-mono text-[9px] uppercase ${state.view === "list" ? "bg-green text-cream" : ""}`}>List</button></div></div>{state.preset === "custom" && <div className="mt-3 flex items-center gap-2"><input aria-label="Range start" type="date" value={state.from} onChange={(event) => { const range = clampCalendarRange(event.target.value, state.to, "from"); go({ preset: "custom", ...range }); }} className="min-w-0 flex-1 border border-ink bg-cream p-2 font-mono text-[10px]"/><span>—</span><input aria-label="Range end" type="date" value={state.to} onChange={(event) => { const range = clampCalendarRange(state.from, event.target.value, "to"); go({ preset: "custom", ...range }); }} className="min-w-0 flex-1 border border-ink bg-cream p-2 font-mono text-[10px]"/></div>}</div>;
}

function CalendarGrid({ data, state, events }: { data: CalendarData; state: CalendarUrlState; events: CalendarEvent[] }) {
  const router = useRouter();
  const cells = monthGrid(state.month, state.weekStart); const byDay = groupCalendarEvents(events); const monthDate = new Date(`${state.month}-01T12:00:00Z`); const labels = state.weekStart === "mon" ? ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] : ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
  const shiftMonth = (delta: number) => { const next = new Date(monthDate); next.setUTCMonth(next.getUTCMonth() + delta); return next.toISOString().slice(0, 7); };
  return <section className="border-2 border-ink bg-surface shadow-[4px_4px_0_var(--color-ink)]"><header className="flex items-center justify-between border-b-2 border-ink p-4"><button onClick={() => router.push(calendarHref(state, { month: shiftMonth(-1) }))} aria-label="Previous month" className="font-mono text-xl">←</button><h2 className="font-heading text-xl font-bold">{new Intl.DateTimeFormat("en-AU", { month: "long", year: "numeric", timeZone: "UTC" }).format(monthDate)}</h2><button onClick={() => router.push(calendarHref(state, { month: shiftMonth(1) }))} aria-label="Next month" className="font-mono text-xl">→</button></header><div className="grid grid-cols-7 border-b border-hairline">{labels.map((label) => <span key={label} className="p-2 text-center font-mono text-[8px] uppercase text-muted">{label}</span>)}</div><div className="grid grid-cols-7">{cells.map((day) => { const rows = byDay.get(day) ?? []; const current = day.startsWith(state.month); return <Link key={day} href={calendarHref(state, { screen: "day", day, back: "calendar" })} className={`min-h-16 border-b border-r border-hairline p-1.5 sm:min-h-24 ${current ? "" : "bg-row text-muted"} ${day === data.today ? "outline-2 -outline-offset-2 outline-green" : ""}`}><span className="font-mono text-[9px] font-bold">{Number(day.slice(-2))}</span><div className="mt-1 flex flex-wrap gap-1 sm:hidden">{rows.slice(0,4).map((event) => <i key={event.key} className={`h-2 w-2 rounded-full ${event.kind === "ranked" ? "bg-green" : event.kind === "cup" ? "bg-chartreuse" : event.kind === "planned" ? "bg-ink" : "bg-crust"}`}/>)}</div><div className="mt-1 hidden space-y-1 sm:block">{rows.slice(0,3).map((event) => <span key={event.key} className={`block truncate px-1 py-0.5 font-mono text-[7px] uppercase ${kindTone[event.kind]}`}>{event.kind === "cup" && <TrophyBadge size={10} className="inline"/>}{event.title}</span>)}</div></Link>; })}</div></section>;
}

function CalendarList({ events, today, state }: { events: CalendarEvent[]; today: string; state: CalendarUrlState }) { const groups = groupCalendarEvents(events); return <div className="space-y-6">{[...groups.entries()].map(([day, rows]) => <section key={day}>{day === today && <div className="mb-3 flex items-center gap-3"><span className="h-px flex-1 bg-green"/><span className="font-mono text-[9px] uppercase text-green">Today</span><span className="h-px flex-1 bg-green"/></div>}<p className={`${eyebrow} mb-2`}>{formatDateKey(day)}</p><div className="grid gap-2">{rows.map((event) => <EventRow key={event.key} event={event} state={state}/>)}</div></section>)}</div>; }
function EventRow({ event, state }: { event: CalendarEvent; state: CalendarUrlState }) { return <Link href={calendarHref(state, { screen: "event", event: event.key, back: state.view === "list" ? "list" : "calendar" })} className="flex items-center justify-between gap-3 border-2 border-ink bg-surface p-4 shadow-[3px_3px_0_var(--color-ink)]"><div className="min-w-0"><span className={`inline-block px-2 py-1 font-mono text-[8px] uppercase ${kindTone[event.kind]}`}>{kindLabel[event.kind]}</span><p className="mt-2 truncate font-heading font-bold">{event.title}</p><p className="truncate font-mono text-[9px] uppercase text-muted">{event.score ?? event.subtitle}{event.metadataMissing ? " · metadata missing" : ""}</p></div><div className="text-right"><p className="font-mono text-sm font-bold text-green">{event.points ? `+${event.points}` : "—"}</p><p className="font-mono text-[8px] uppercase text-muted">{event.status.replace("_", " ")}</p></div></Link>; }

function DayDetail({ day, events, state }: { day: string; events: CalendarEvent[]; state: CalendarUrlState }) { return <section className="mx-auto max-w-3xl"><BackLink href={calendarHref(state, { screen: "calendar", day: null })}>Calendar</BackLink><p className={`${eyebrow} mt-7`}>Day detail</p><h1 className="font-heading text-4xl font-bold">{formatDateKey(day)}</h1><div className="mt-6 grid gap-3">{events.length ? events.map((event) => <EventRow key={event.key} event={event} state={state}/>) : <p className="border-2 border-dashed border-hairline bg-surface p-6 text-muted">No tennis recorded on this day.</p>}</div></section>; }
function EventDetail({ event, state }: { event: CalendarEvent; state: CalendarUrlState }) { const back = state.back === "day" && state.day ? calendarHref(state, { screen: "day", event: null }) : calendarHref(state, { screen: "calendar", event: null }); return <section className="mx-auto max-w-3xl"><BackLink href={back}>{state.back === "day" ? "Day" : "Calendar"}</BackLink><article className="mt-7 border-2 border-ink bg-surface p-6 shadow-[5px_5px_0_var(--color-ink)]"><div className="flex items-start justify-between gap-4"><div><span className={`inline-block px-2 py-1 font-mono text-[9px] uppercase ${kindTone[event.kind]}`}>{kindLabel[event.kind]}</span><h1 className="mt-3 font-heading text-3xl font-bold">{event.title}</h1><p className="mt-1 font-mono text-[10px] uppercase text-muted">{formatDay(event.startsAt, true)} · {event.status.replace("_", " ")}</p></div>{event.kind === "cup" && <TrophyBadge size={42}/>}</div><div className="mt-6 grid gap-4 border-y border-hairline py-5 sm:grid-cols-3"><Detail label="Result" value={event.score ?? event.subtitle}/><Detail label="Points" value={event.points ? `+${event.points}` : "—"}/><Detail label="Surface" value={event.surface ?? "Not recorded"}/><Detail label="Court" value={event.kind === "practice" ? "Not recorded" : event.court ?? event.location ?? "Not recorded"}/>{event.record && <Detail label="Fixture record" value={`${event.record.won}-${event.record.lost}`}/>} </div>{event.metadataMissing && <Link href="/matches/untagged" className="mt-5 block border border-dashed border-crust p-3 font-mono text-[10px] uppercase text-crust">Complete missing court or surface →</Link>}<Link href={event.href} className="mt-6 inline-block font-mono text-[11px] uppercase text-green underline decoration-2 underline-offset-4">Open source record →</Link></article></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className={eyebrow}>{label}</p><p className="mt-1 font-heading font-bold">{value}</p></div>; }
function formatDateKey(day: string) { return new Intl.DateTimeFormat("en-AU", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${day}T12:00:00Z`)); }
function formatDay(value: string, time = false) { return new Intl.DateTimeFormat("en-AU", { weekday: "short", day: "numeric", month: "short", ...(time ? { hour: "numeric", minute: "2-digit" } : {}), timeZone: "Australia/Melbourne" }).format(new Date(value)); }
