import Link from "next/link";
import { redirect } from "next/navigation";
import { getSessionPlayer } from "@/lib/auth/session";
import { SiteHeader } from "@/components/layout/SiteHeader";
const earns = [
  { points: "VARIES", title: "Cup placement", body: "Finish a cup and collect its published placement award.", href: "/tournaments", cta: "See open cups" },
  { points: "+30 / +15", title: "Ranked match", body: "Both players earn +15; the winner earns another +15 after approval.", href: "/matches/new?type=ranked", cta: "Log a ranked match" },
  { points: "+10", title: "Non-ranked match", body: "Exhibition players and a Non-Ciabatta participant earn a flat ten.", href: "/matches/new?type=exhibition", cta: "Log a non-ranked match" },
  { points: "+5", title: "Solo practice", body: "Solo work earns five after organiser approval.", href: "/practice/new", cta: "Log solo practice" },
];
export default async function PointsPage() { const player = await getSessionPlayer(); if (!player) redirect("/sign-in"); return <main className="mx-auto flex w-full max-w-5xl flex-1 flex-col px-4 py-5 sm:px-6"><SiteHeader role={player.role} active="points"/><header className="mb-6"><p className="font-mono text-[10px] uppercase tracking-[2px] text-muted">The economy of effort</p><h1 className="font-heading text-3xl font-bold">How points work</h1></header><section className="grid gap-4 sm:grid-cols-2">{earns.map((item) => <article key={item.title} className="flex flex-col border-2 border-ink bg-surface p-5 shadow-[3px_3px_0_var(--color-ink)]"><span className="self-start border border-green px-2 py-1 font-mono text-[10px] font-bold text-green">{item.points}</span><h2 className="mt-3 font-heading text-xl font-bold">{item.title}</h2><p className="mt-2 flex-1 font-body text-sm text-muted">{item.body}</p><Link href={item.href} className="mt-5 font-mono text-xs uppercase text-green underline">{item.cta} →</Link></article>)}</section><section className="mt-6 border-2 border-ink bg-ink p-6 text-cream shadow-[4px_4px_0_var(--color-rust)]"><p className="font-mono text-[10px] uppercase tracking-[2px] text-green-muted">Ways to lose</p><h2 className="mt-1 font-heading text-2xl font-bold">Keep showing up</h2><ul className="mt-4 grid gap-3 font-body text-sm"><li><strong className="font-mono text-rust">−1</strong> each day without tennis</li><li><strong className="font-mono text-rust">−10</strong> after every completed 7-day drought stretch</li><li><strong className="font-mono text-rust">−30</strong> after every completed 30-day drought stretch</li></ul><p className="mt-5 font-mono text-[10px] uppercase text-green-muted">Any tennis resets the drought clock. Lost points stay lost. Totals never fall below zero.</p></section></main>; }
